version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    container_name: api_container
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - mongo

volumes:
  mongo_data:
